/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author Cristy
 */
public class ChatCliente extends javax.swing.JFrame {

    /**
     * Creates new form ChatCliente
     */
    Controlador c;
    String nombre;
    
    public ChatCliente() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Chat ACR_2018");
        setIconImage(new ImageIcon(getClass().getResource("../extras/icons8_Chat_35px.png")).getImage());
        this.c = null;        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        nombreUsuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        contactosMandarMensaje = new javax.swing.JComboBox();
        salir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        contactosConectados = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMensajes = new javax.swing.JTextArea();
        mensaje = new javax.swing.JTextField();
        enviarMensaje = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        nombreUsuario.setBackground(new java.awt.Color(0, 0, 102));
        nombreUsuario.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        nombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        nombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/icons8_Male_User_35px.png"))); // NOI18N
        nombreUsuario.setText("Usuario:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/icons8_User_Groups_25px.png"))); // NOI18N
        jLabel2.setText("Contactos en línea");

        contactosMandarMensaje.setBackground(new java.awt.Color(0, 51, 102));
        contactosMandarMensaje.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        contactosMandarMensaje.setForeground(new java.awt.Color(255, 255, 255));
        contactosMandarMensaje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos" }));

        salir.setBackground(new java.awt.Color(0, 0, 102));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/icons8_Exit_25px.png"))); // NOI18N
        salir.setBorder(null);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        contactosConectados.setEditable(false);
        contactosConectados.setBackground(new java.awt.Color(0, 51, 102));
        contactosConectados.setColumns(20);
        contactosConectados.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N
        contactosConectados.setForeground(new java.awt.Color(255, 255, 255));
        contactosConectados.setRows(5);
        jScrollPane2.setViewportView(contactosConectados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(contactosMandarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(contactosMandarMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        areaMensajes.setEditable(false);
        areaMensajes.setColumns(20);
        areaMensajes.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        areaMensajes.setRows(5);
        jScrollPane1.setViewportView(areaMensajes);

        mensaje.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 16)); // NOI18N

        enviarMensaje.setBackground(new java.awt.Color(0, 0, 102));
        enviarMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/extras/icons8_Message_35px_1.png"))); // NOI18N
        enviarMensaje.setBorder(null);
        enviarMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarMensajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enviarMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mensaje)
                    .addComponent(enviarMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarMensajeActionPerformed
        String accion = "";
        if(!this.mensaje.getText().equals("")){
            if(((String)contactosMandarMensaje.getSelectedItem()).equals("Todos")){
                accion = "Publico#"+mensaje.getText();
            }else{
                String nombreContacto = (String)contactosMandarMensaje.getSelectedItem();
                accion = "Privado#"+nombreContacto+"#"+mensaje.getText();
            }
            this.c.enviarComando(accion);
        }

        mensaje.setText("");
    }//GEN-LAST:event_enviarMensajeActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        this.c.enviarComando("SALIDA");
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMensajes;
    private javax.swing.JTextArea contactosConectados;
    private javax.swing.JComboBox contactosMandarMensaje;
    private javax.swing.JButton enviarMensaje;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mensaje;
    public static javax.swing.JLabel nombreUsuario;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

    public void setConectados(ArrayList<String> conectados){
        this.contactosConectados.setText("");
        this.contactosMandarMensaje.removeAllItems();
        this.contactosMandarMensaje.addItem("Todos");
        
        if(conectados.isEmpty()){
            this.contactosConectados.setText("Sin contactos en línea. \n Espera, por favor :)");
        }else{
            for(String usuario : conectados){
                this.contactosConectados.setText(this.contactosConectados.getText()+usuario+"\n");
                this.contactosMandarMensaje.addItem(new String(usuario));
            }
        }
    }
    
    public void addUsuario(String s){
        if(this.contactosConectados.getText().equals("Sin contactos en línea. \n Espera, por favor :)")){
            this.contactosConectados.setText(s+"\n");
        }else{
            this.contactosConectados.setText(this.contactosConectados.getText()+s+"\n");
        }
        this.contactosMandarMensaje.addItem(new String(s));
    }
    
    public void quitarConectado(String s){
        ArrayList<String> nuevaLista = new ArrayList<>();
        int pos = 0;
        String aux = "";
        
        while(pos<this.contactosConectados.getText().length()){
            if(this.contactosConectados.getText().charAt(pos)!='\n'){
                aux += this.contactosConectados.getText().charAt(pos);
            }else{
                nuevaLista.add(aux);
                aux = "";
            }
            pos++;
        }
        
        if(nuevaLista.isEmpty()){
            this.contactosConectados.setText("Sin contactos en línea. \n Espera, por favor :)");
        }else{
            for(String saux : nuevaLista){
                if(saux.equals(s)){
                    nuevaLista.remove(saux);
                    break;
                }
            }
            if(nuevaLista.isEmpty()){
                this.contactosConectados.setText("Sin contactos en línea. \n Espera, por favor :)");
            }else{
                for(String saux : nuevaLista){
                    this.addUsuario(saux);
                }
                //setConectados(nuevaLista);
            }
        }
        
        int posU = -1;
        
        for(int i=0;i<this.contactosMandarMensaje.getItemCount();i++){
            if(((String)this.contactosMandarMensaje.getItemAt(i)).equals(s))
                posU = i;
        }
        this.contactosMandarMensaje.removeItemAt(posU);
    }
   
    public void setNombre(String nombre){
        this.nombre = nombre;
    }
    
    public void setControlador(Controlador c){
        this.c = c;
    }
    
    public void escribirEnArea(String texto){
        this.areaMensajes.setText(this.areaMensajes.getText()+texto+"\n");  
    }
    
    
}
